/* ****  Dont use days 1 and 2  **** */


CREATE TABLE CUSTOMER_DETAILS ( 
CNIC VARCHAR(25) NOT NULL PRIMARY KEY,
FNAME VARCHAR(25) NOT NULL,   
LNAME VARCHAR(25) NOT NULL,   
PHONE_NUMBER VARCHAR(15) NOT NULL,   
EMAIL_ID VARCHAR(30) NOT NULL,    
PASSWORD1 VARCHAR(20) NOT NULL,
MEMBERSHIP_ID VARCHAR(25)   
); 

CREATE TABLE CAR_CATEGORY ( 
CATEGORY_NAME VARCHAR(25) NOT NULL PRIMARY KEY,      
COST_PER_DAY VARCHAR(25) NOT NULL,   
LATE_FEE_PER_DAY VARCHAR(25) NOT NULL   
); 

CREATE TABLE LOCATION_DETAILS (
NUMBER_OF_DAYS VARCHAR(25),   
PICKUP_LOCATION VARCHAR(50) NOT NULL,
DROPOFF_LOCATION VARCHAR(50) NOT NULL
);

CREATE TABLE BOOKING_DETAILS ( 
BOOKING_ID CHAR(5) NOT NULL PRIMARY KEY,
CATEGORY VARCHAR(25),
AVAILABLE VARCHAR(25),
DRIVER VARCHAR(25),
MAKE VARCHAR(25),
MODEL VARCHAR(25)
);

CREATE TABLE ADMIN_DETAILS (
ADMIN_ID CHAR(8) NOT NULL PRIMARY KEY,
PASSWORD2 VARCHAR(25) NOT NULL,
FNAME VARCHAR(25) NOT NULL,
LNAME VARCHAR(25) NOT NULL,
PHONE_NUMBER VARCHAR(25) NOT NULL, 
EMAIL_ID VARCHAR(30) NOT NULL,
);



/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 100 [CNIC]
      ,[FNAME]
      ,[LNAME]
      ,[PHONE_NUMBER]
      ,[EMAIL_ID]
      ,[PASSWORD1]
      ,[MEMBERSHIP_ID]
  FROM [CarRentalSystemDBMSProject].[dbo].[CUSTOMER_DETAILS]

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 100 [CATEGORY_NAME]
      ,[COST_PER_DAY]
      ,[LATE_FEE_PER_DAY]
  FROM [CarRentalSystemDBMSProject].[dbo].[CAR_CATEGORY]

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 100 [NUMBER_OF_DAYS]
      ,[PICKUP_LOCATION]
      ,[DROPOFF_LOCATION]
  FROM [CarRentalSystemDBMSProject].[dbo].[LOCATION_DETAILS]

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 100 [BOOKING_ID]
      ,[CATEGORY]
      ,[AVAILABLE]
      ,[DRIVER]
      ,[MAKE]
      ,[MODEL]
  FROM [CarRentalSystemDBMSProject].[dbo].[BOOKING_DETAILS]

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 100 [ADMIN_ID]
      ,[PASSWORD2]
      ,[FNAME]
      ,[LNAME]
      ,[PHONE_NUMBER]
      ,[EMAIL_ID]
  FROM [CarRentalSystemDBMSProject].[dbo].[ADMIN_DETAILS]